---
- name: Building Ansible Network Inventory
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Network Resource Manager
      ansible.builtin.include_role:
        name: resource_manager
      vars:
        action: persist
        resources:
          - 'interfaces'
          - 'l3_interfaces'
